#! /usr/bin/env python

"""Visualize Symbolic Navigation Goal

Usage:
  visualize-symbolic-navigation-goal [<robot_name> <entity_id> <volume_name>]...

Examples:
  visualize-symbolic-navigation-goal amigo plastic_cabinet in_front_of
  visualize-symbolic-navigation-goal hero plastic_cabinet in_front_of living_room in
"""

import rospy
import sys
from ed_navigation_msgs.srv import GetGoalConstraint
from cb_base_navigation_msgs.srv import GetPlan
from cb_base_navigation_msgs.msg import PositionConstraint
from docopt import docopt

if __name__ == "__main__":
    rospy.init_node("visualize_symbolic_navigation_goal")

    arguments = docopt(__doc__, argv=rospy.myargv)
    print(f"Visualizing the following symbolic constraints:\n{arguments}")

    robot_name = arguments["<robot_name>"][0]

    try:
        constraint_srv = rospy.ServiceProxy(f"/{robot_name}/ed/navigation/get_constraint", GetGoalConstraint)
        resp = constraint_srv(
            entity_ids=[c for c in arguments["<entity_id>"]], area_names=[a for a in arguments["<volume_name>"]]
        )
        print(f"Constraint in map frame:\n{resp.position_constraint_map_frame}")

        plan_srv = rospy.ServiceProxy(f"/{robot_name}/global_planner/get_plan_srv", GetPlan)
        plan_srv(
            goal_position_constraints=[PositionConstraint(frame="map", constraint=resp.position_constraint_map_frame)]
        )
        print("** Published Visualization Marker **")
    except rospy.ServiceException as e:
        print(f"Service call failed: {e}")
